--Não precisa chamar na aplicação nada destes arquivos!

INSERT INTO FEDERACAO (NOME, DATA_FUND) VALUES ('Federação A', TO_DATE('2020-01-01', 'YYYY-MM-DD'));
INSERT INTO NACAO (NOME, QTD_PLANETAS, FEDERACAO) VALUES ('Nação A', 3, 'Federação A');
INSERT INTO PLANETA (ID_ASTRO, MASSA, RAIO, CLASSIFICACAO) VALUES ('Planeta A', 5.972, 6371, 'Classe M');
INSERT INTO ESPECIE (NOME, PLANETA_OR, INTELIGENTE) VALUES ('Espécie A', 'Planeta A', 'V');
INSERT INTO LIDER (CPI, NOME, CARGO, NACAO, ESPECIE) VALUES ('123.123.123-10', 'Líder A', 'COMANDANTE', 'Nação A', 'Espécie A');
INSERT INTO FACCAO (NOME, LIDER, IDEOLOGIA, QTD_NACOES) VALUES ('Facção A', '123.123.123-10', 'PROGRESSITA', 1);
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Nação A', 'Facção A');
INSERT INTO DOMINANCIA (PLANETA, NACAO, DATA_INI) VALUES ('Planeta A', 'Nação A', TO_DATE('2020-01-01', 'YYYY-MM-DD'));
INSERT INTO COMUNIDADE (ESPECIE, NOME, QTD_HABITANTES) VALUES ('Espécie A', 'Comunidade A', 1000);
INSERT INTO HABITACAO (PLANETA, ESPECIE, COMUNIDADE, DATA_INI) VALUES ('Planeta A', 'Espécie A', 'Comunidade A', TO_DATE('0009-09-09', 'YYYY-MM-DD'));





CREATE OR REPLACE PROCEDURE insert_missing_leaders AS
BEGIN
	FOR r IN (
		SELECT l.CPI 
		FROM LIDER l
		LEFT JOIN USERS u ON l.CPI = u.Lider
		WHERE u.Lider IS NULL
	) LOOP
		INSERT INTO USERS (Lider, Password) 
		VALUES (r.CPI, 'admin');
	END LOOP;

	COMMIT;
END;
/